name: Build Svelte on Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: ./web/package-lock.json
      
      - name: Install dependencies
        run: |
          cd web
          npm ci
      
      - name: Build Svelte
        run: |
          cd web
          npm run build
      
      - name: Commit and push build files
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add -f web/build
          git commit -m "Build Svelte app for release ${{ github.event.release.tag_name }}" || echo "No changes to commit"
          git push origin HEAD:${GITHUB_REF}