name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main
          
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
          
      - name: Install dependencies
        run: cd web && bun install
        
      - name: Build Svelte
        run: cd web && bun run build
        
      - name: Bundle files
        run: |
          mkdir -p ./temp/hype_banking
          mkdir -p ./temp/hype_banking/web/build
          cp -r ./bridge ./temp/hype_banking/
          cp -r ./client ./temp/hype_banking/
          cp -r ./locales ./temp/hype_banking/
          cp -r ./server ./temp/hype_banking/
          cp -r ./shared ./temp/hype_banking/
          cp -r ./web/build ./temp/hype_banking/web/build
          cp ./fxmanifest.lua ./temp/hype_banking/
          cd ./temp && zip -r ../hype_banking.zip ./hype_banking
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ github.ref_name }}
          draft: false
          prerelease: false
          generate_release_notes: true
          files: hype_banking.zip
